import { constants } from "node:fs";
import { access, chmod, copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { homedir } from "node:os";

const VALID_TARGETS = new Set(["all", "env", "cursor"]);

export async function runSetup(options = {}) {
  const context = {
    baseUrl: normalizeBaseUrl(options.baseUrl ?? "http://localhost:6767"),
    home: options.home ?? homedir(),
    dryRun: Boolean(options.dryRun),
    target: options.target ?? "all"
  };

  if (!VALID_TARGETS.has(context.target)) {
    throw new Error(`Unsupported setup target: ${context.target}`);
  }

  const apiKey = await readApiKey(join(context.home, ".supermemory", "api-key"));
  const actions = [];

  if (context.target === "all" || context.target === "env") {
    actions.push(await setupEnvFile(context, apiKey));
  }

  if (context.target === "all" || context.target === "cursor") {
    actions.push(await setupCursorMcp(context, apiKey));
  }

  if (context.target === "all") {
    actions.push(...manualInstallerActions());
  }

  const summary = summarize(actions);
  const result = {
    command: "setup",
    generatedAt: new Date().toISOString(),
    baseUrl: context.baseUrl,
    dryRun: context.dryRun,
    target: context.target,
    summary,
    actions: actions.map(redactAction),
    exitCode: summary.failed > 0 ? 1 : 0
  };
  result.text = formatSetup(result);
  return result;
}

async function setupEnvFile(context, apiKey) {
  const path = join(context.home, ".config", "smctl", "supermemory.env");
  const content = [
    "# Generated by smctl setup. Keep this file private.",
    `export SUPERMEMORY_BASE_URL="${context.baseUrl}"`,
    `export SUPERMEMORY_API_KEY="${apiKey}"`,
    `export SUPERMEMORY_CC_API_KEY="${apiKey}"`,
    `export SUPERMEMORY_CODEX_API_KEY="${apiKey}"`,
    ""
  ].join("\n");

  return writeManagedFile({
    title: "Write Supermemory shell env file",
    path,
    content,
    mode: 0o600,
    dryRun: context.dryRun
  });
}

async function setupCursorMcp(context, apiKey) {
  const path = join(context.home, ".cursor", "mcp.json");
  let data = {};
  let existing = null;

  if (await exists(path)) {
    existing = await readFile(path, "utf8");
    try {
      data = JSON.parse(existing);
    } catch {
      return {
        status: "failed",
        title: "Configure Cursor MCP",
        path,
        detail: "Existing ~/.cursor/mcp.json is not valid JSON; leaving it untouched"
      };
    }
  }

  data.mcpServers = data.mcpServers && typeof data.mcpServers === "object" ? data.mcpServers : {};
  data.mcpServers["supermemory-local"] = {
    url: `${context.baseUrl}/mcp`,
    headers: {
      Authorization: `Bearer ${apiKey}`
    }
  };

  const content = `${JSON.stringify(data, null, 2)}\n`;
  return writeManagedFile({
    title: "Configure Cursor MCP",
    path,
    content,
    mode: 0o600,
    dryRun: context.dryRun
  });
}

async function writeManagedFile({ title, path, content, mode, dryRun }) {
  const existed = await exists(path);
  const oldContent = existed ? await readFile(path, "utf8") : null;

  if (oldContent === content) {
    return {
      status: "unchanged",
      title,
      path,
      detail: "Already configured"
    };
  }

  if (dryRun) {
    return {
      status: existed ? "would-update" : "would-create",
      title,
      path,
      detail: existed ? "Would create a timestamped backup before updating" : "Would create file"
    };
  }

  await mkdir(dirname(path), { recursive: true });
  let backupPath = null;
  if (existed) {
    backupPath = `${path}.bak-${timestamp()}`;
    await copyFile(path, backupPath);
    await chmod(backupPath, mode);
  }

  await writeFile(path, content, { mode });
  await chmod(path, mode);

  return {
    status: existed ? "updated" : "created",
    title,
    path,
    backupPath,
    detail: existed ? "Updated with backup" : "Created"
  };
}

function manualInstallerActions() {
  return [
    {
      status: "manual",
      title: "Load Harness env in your shell",
      detail: "source ~/.config/smctl/supermemory.env"
    },
    {
      status: "manual",
      title: "Install Claude Code plugin",
      detail: "/plugin marketplace add supermemoryai/claude-supermemory && /plugin install claude-supermemory"
    },
    {
      status: "manual",
      title: "Install Codex plugin",
      detail: "npx codex-supermemory@latest install"
    },
    {
      status: "manual",
      title: "Install OpenCode plugin",
      detail: "bunx opencode-supermemory@latest install"
    }
  ];
}

async function readApiKey(path) {
  if (!await exists(path)) {
    throw new Error("Supermemory API key file not found at ~/.supermemory/api-key");
  }
  const apiKey = (await readFile(path, "utf8")).trim();
  if (!apiKey.startsWith("sm_") || apiKey.length < 80) {
    throw new Error("Supermemory API key file exists but has an unexpected shape");
  }
  return apiKey;
}

function formatSetup(result) {
  const lines = [];
  lines.push("Supermemory Harness setup");
  lines.push(`Base URL: ${result.baseUrl}`);
  lines.push(`Mode: ${result.dryRun ? "dry-run" : "write"}`);
  lines.push(`Summary: ${result.summary.created} created, ${result.summary.updated} updated, ${result.summary.unchanged} unchanged, ${result.summary["would-create"]} would-create, ${result.summary["would-update"]} would-update, ${result.summary.manual} manual, ${result.summary.failed} failed`);
  lines.push("");

  for (const action of result.actions) {
    lines.push(`${symbol(action.status)} ${action.title}`);
    if (action.path) {
      lines.push(`   ${redactHome(action.path)}`);
    }
    if (action.backupPath) {
      lines.push(`   backup: ${redactHome(action.backupPath)}`);
    }
    if (action.detail) {
      lines.push(`   ${action.detail}`);
    }
  }

  lines.push("");
  if (result.summary.failed > 0) {
    lines.push("Result: setup could not complete every action.");
  } else if (result.dryRun) {
    lines.push("Result: dry-run completed; no files were changed.");
  } else {
    lines.push("Result: local setup files are ready.");
  }
  return lines.join("\n");
}

function summarize(actions) {
  return actions.reduce((acc, action) => {
    acc[action.status] = (acc[action.status] ?? 0) + 1;
    return acc;
  }, {
    created: 0,
    updated: 0,
    unchanged: 0,
    "would-create": 0,
    "would-update": 0,
    manual: 0,
    failed: 0
  });
}

function symbol(status) {
  if (status === "created" || status === "updated" || status === "unchanged") return "[ok]";
  if (status === "would-create" || status === "would-update") return "[plan]";
  if (status === "manual") return "[next]";
  return "[fail]";
}

function redactAction(action) {
  return {
    ...action,
    path: action.path ? redactHome(action.path) : undefined,
    backupPath: action.backupPath ? redactHome(action.backupPath) : undefined
  };
}

async function exists(path) {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

function normalizeBaseUrl(url) {
  return url.endsWith("/") ? url.slice(0, -1) : url;
}

function redactHome(path) {
  const home = homedir();
  if (path === home) return "~";
  if (path.startsWith(`${home}/`)) return `~/${path.slice(home.length + 1)}`;
  return path;
}

function timestamp() {
  return new Date().toISOString().replace(/[:.]/g, "-");
}
